input_image_shape: (1, 28, 28)
cnn_vae:
  vae_encoder_params:
    conv1_out_channels: 64
    conv2_out_channels: 128
    linear1_out_layer: 1024
    kernel_size: 4
    stride: 2
    padding: 1
    activation: 'relu'
    latent_dim: 32
  vae_dencoder_params:
    latent_dim: 32
    linear1_out_layer: 1024,
    conv2_out_channels: 128,
    conv1_out_channels: 64,
    kernel_size: 4,
    stride: 2,
    padding: 1,
    activation: 'relu',
    last_activation: 'sigmoid'