input_image_shape:
  input_image_shape_c: 1
  input_image_shape_h: 28
  input_image_shape_w: 28
cnn_vae:
  vae_encoder_params:
    conv1_out_channels: 64
    conv2_out_channels: 128
    linear1_out_layer: 1024
    kernel_size: 4
    stride: 2
    padding: 1
    activation: 'relu'
    latent_dim: 32
  vae_decoder_params:
    activation: 'relu'
    last_activation: 'sigmoid'